CREATE OR REPLACE PACKAGE BODY PKG_EXAMPLE
AS

PROCEDURE EXAMPLE_1
AS
	nLOG_RUN_ID NUMBER := PKG_LOGS.PREPARE_RUN_ID(NULL);
BEGIN
	PKG_LOGS.ADD_LOG(DESCR 	=>'EXAMPLE_1 BEG', 
				vLOG_THEME	=> 'example', 
				vLOG_TYPE 	=> 'INFO',
				RUN_ID		=> nLOG_RUN_ID);

	PKG_LOGS.ADD_LOG(DESCR 	=>'EXAMPLE_1 warning', 
				vLOG_THEME 	=> 'example', 
				vLOG_TYPE 	=> 'warning',
				RUN_ID		=> nLOG_RUN_ID);
						
	PKG_EXAMPLE.EXAMPLE_2(LOG_RUN_ID => nLOG_RUN_ID);

	PKG_LOGS.ADD_LOG(DESCR 	=>'EXAMPLE_1 END', 
				vLOG_THEME 	=> 'example', 
				vLOG_TYPE 	=> 'INFO',
				RUN_ID		=> nLOG_RUN_ID);
END	EXAMPLE_1;

PROCEDURE EXAMPLE_2(LOG_RUN_ID IN NUMBER DEFAULT NULL)
AS
	nLOG_RUN_ID NUMBER := PKG_LOGS.PREPARE_RUN_ID(LOG_RUN_ID);
BEGIN
	PKG_LOGS.ADD_LOG(DESCR 	=>'EXAMPLE_2 BEG', 
				vLOG_THEME	=> 'example', 
				vLOG_TYPE 	=> 'INFO',
				RUN_ID		=> nLOG_RUN_ID);
						
	PKG_LOGS.ADD_LOG(DESCR 	=>'EXAMPLE_2 END', 
				vLOG_THEME	=> 'example', 
				vLOG_TYPE 	=> 'INFO',
				RUN_ID		=> nLOG_RUN_ID);
END	EXAMPLE_2;

END PKG_EXAMPLE;