CREATE TABLE LOGS_NAME
(ID 		NUMBER(38,0), 
NAME 		VARCHAR2(4000) NOT NULL, 
ACTIVE 		VARCHAR2(1) DEFAULT 'Y' NOT NULL,
CLEAR_TIME_TYPE	NUMBER(38,0) NOT NULL, 
DAYS_CNT	NUMBER(38,0), 
MONTHS_CNT	NUMBER(38,0),
DESCR 		VARCHAR2(4000),
CONSTRAINT LOG_NAME_PK PRIMARY KEY (ID), 
CONSTRAINT LOG_NAME_UN UNIQUE (NAME),
CONSTRAINT LOGS_NAME_CHECK_DAYS_MONTHS CHECK ("CLEAR_TIME_TYPE"=1 AND "DAYS_CNT" IS NOT NULL AND "MONTHS_CNT" IS NULL OR "CLEAR_TIME_TYPE"=2 AND "DAYS_CNT" IS NULL AND "MONTHS_CNT" IS NOT NULL), 
CONSTRAINT LOGS_NAME_CHECK_ACTIVE CHECK (ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE LOG_NAME_SEQ
	START WITH 1
	INCREMENT BY 1
	CACHE 20
	NOCYCLE;

CREATE OR REPLACE TRIGGER LOG_NAME_I 
	BEFORE INSERT
		ON LOGS_NAME
	FOR EACH ROW
DECLARE
BEGIN
	:NEW.ID := LOG_NAME_SEQ.nextval;
END LOG_NAME_I;

COMMENT ON TABLE LOGS_NAME IS 'Наименование лога';
COMMENT ON COLUMN LOGS_NAME.ID IS 'Первичный ключ';
COMMENT ON COLUMN LOGS_NAME.NAME IS 'Наименование';
COMMENT ON COLUMN LOGS_NAME.ACTIVE IS 'Собирать логи';