CREATE TABLE LOGS_NAME
(ID 	NUMBER(38,0), 
NAME 	VARCHAR2(4000) NOT NULL, 
ACTIVE 	VARCHAR2(1) DEFAULT 'Y' NOT NULL, 
CONSTRAINT LOG_NAME_PK PRIMARY KEY (ID), 
CONSTRAINT LOG_NAME_UN UNIQUE (NAME)
);

CREATE SEQUENCE LOG_NAME_SEQ
	START WITH 1
	INCREMENT BY 1
	CACHE 20
	NOCYCLE;

CREATE OR REPLACE EDITIONABLE TRIGGER LOG_NAME_I 
	BEFORE INSERT
		ON LOGS_NAME
	FOR EACH ROW
DECLARE
BEGIN
	:NEW.ID := LOG_NAME_SEQ.nextval;
END LOG_NAME_I;

COMMENT ON TABLE LOGS_NAME IS 'Наименование лога';
COMMENT ON COLUMN LOGS_NAME.ID IS 'Первичный ключ';
COMMENT ON COLUMN LOGS_NAME.NAME IS 'Наименование';
COMMENT ON COLUMN LOGS_NAME.ACTIVE IS 'Собирать логи';