CREATE TABLE LOGS_TYPE
(ID 		NUMBER(38,0), 
LOG_TYPE 	VARCHAR2(100), 
CONSTRAINT LOGS_TYPE_PK PRIMARY KEY (ID),
CONSTRAINT LOGS_TYPE_UN UNIQUE (LOG_TYPE)
);

CREATE SEQUENCE LOGS_TYPE_SEQ
	START WITH 1
	INCREMENT BY 1
	CACHE 20
	NOCYCLE;

CREATE OR REPLACE TRIGGER LOGS_TYPE_I 
	BEFORE INSERT
		ON LOGS_TYPE
	FOR EACH ROW
DECLARE
BEGIN
	:NEW.ID := LOGS_TYPE_SEQ.nextval;
END LOGS_TYPE_I;

COMMENT ON TABLE LOGS_TYPE IS 'Тип логов';
COMMENT ON COLUMN LOGS_TYPE.ID IS 'Первичный ключ';
COMMENT ON COLUMN LOGS_TYPE.LOG_TYPE IS 'Тип лога';