CREATE TABLE LOGS
(ID 			NUMBER(38,0),
RUN_ID			NUMBER(38,0) NOT NULL,
LOG_TYPE_ID 	NUMBER(38,0) NOT NULL,
DESCR			VARCHAR2(4000),
LOG_NAME_ID		NUMBER(38,0) NOT NULL,
CREATE_USER_ID 	NUMBER(38,0),
CREATE_USER 	VARCHAR2(100) NOT NULL, 
CREATE_DATE 	DATE NOT NULL, 
APP_ID			NUMBER(38,0), 
PAGE_ID			NUMBER(38,0), 
PROG_NAME		VARCHAR2(4000), 
DESCR_CLOB		CLOB, 
CONSTRAINT LOGS_PK PRIMARY KEY (ID), 
CONSTRAINT FK_LOGS_TYPE_ID FOREIGN KEY (LOG_TYPE_ID) REFERENCES LOGS_TYPE (ID), 
CONSTRAINT FK_LOGS_NAME_ID FOREIGN KEY (LOG_NAME_ID) REFERENCES LOGS_NAME (ID)
);

CREATE SEQUENCE LOGS_SEQ
	START WITH 1
	INCREMENT BY 1
	CACHE 100
	NOCYCLE;

CREATE OR REPLACE TRIGGER LOGS_I 
	BEFORE INSERT
		ON LOGS
	FOR EACH ROW
DECLARE
	vUSER 		VARCHAR2(4000);
	nUSER_ID	NUMBER;
BEGIN
	
	:NEW.ID := LOGS_SEQ.nextval;
	
	DBADMINDATA.PKG_USERS.get_user(vUSER,nUSER_ID);
	:NEW.CREATE_DATE := SYSDATE;
	:NEW.CREATE_USER_ID := nUSER_ID;
	:NEW.CREATE_USER := vUSER;
	:NEW.APP_ID := V('APP_ID');
	:NEW.PAGE_ID := V('PAGE_ID');
END LOGS_I;

COMMENT ON TABLE LOGS IS 'Логи';
COMMENT ON COLUMN LOGS.ID IS 'Первичный ключ';
COMMENT ON COLUMN LOGS.RUN_ID IS 'ID группы логов';
COMMENT ON COLUMN LOGS.LOG_TYPE_ID IS 'Ссылка на LOGS_TYPE';
COMMENT ON COLUMN LOGS.DESCR IS 'Описание';
COMMENT ON COLUMN LOGS.LOG_NAME_ID IS 'ID названия лога';
COMMENT ON COLUMN LOGS.CREATE_USER_ID IS 'ID пользователя';
COMMENT ON COLUMN LOGS.CREATE_USER IS 'Имя пользователя';
COMMENT ON COLUMN LOGS.CREATE_DATE IS 'Дата создания';
COMMENT ON COLUMN LOGS.APP_ID IS 'Приложение';
COMMENT ON COLUMN LOGS.PAGE_ID IS 'Страница';
COMMENT ON COLUMN LOGS.PROG_NAME IS 'Программа запуска';
COMMENT ON COLUMN LOGS.DESCR_CLOB IS 'Описание CLOB';