CREATE OR REPLACE VIEW V_LOGS ("ID", "RUN_ID", "LOG_TYPE_ID", "LOG_TYPE", "DESCR", "LOG_THEME_ID", "THEME_NAME", "ACTIVE", "CLEAR_TIME_TYPE", "DAYS_CNT", "MONTHS_CNT", "CREATE_USER_ID", "CREATE_USER", "CREATE_DATE", "APP_ID", "PAGE_ID", "PROG_NAME", "DESCR_CLOB") AS 
  SELECT l.ID, 
			l.RUN_ID, 
			l.LOG_TYPE_ID,
			t.LOG_TYPE,
			l.DESCR, 
			l.LOG_THEME_ID,
			n.THEME_NAME,
			n.ACTIVE,
			n.CLEAR_TIME_TYPE,
			n.DAYS_CNT,
			n.MONTHS_CNT,
			l.CREATE_USER_ID, 
			l.CREATE_USER, 
			l.CREATE_DATE, 
			l.APP_ID, 
			l.PAGE_ID, 
			l.PROG_NAME, 
			l.DESCR_CLOB
		FROM LOGS l
		LEFT JOIN LOGS_THEMES n
			ON l.LOG_THEME_ID = n.ID
		LEFT JOIN LOGS_TYPE t
			ON l.LOG_TYPE_ID = t.ID;