CREATE OR REPLACE PACKAGE PKG_LOGS
AS

FUNCTION GET_RUN_ID RETURN NUMBER;

FUNCTION PREPARE_RUN_ID (RUN_ID IN NUMBER) RETURN NUMBER;

PROCEDURE ADD_LOG(DESCR  		IN VARCHAR2,
				LOG_THEME_ID	IN NUMBER,
				LOG_TYPE_ID		IN NUMBER 	DEFAULT NULL,
				RUN_ID 			IN NUMBER 	DEFAULT NULL,
				DESCR_CLOB		IN CLOB 	DEFAULT NULL,
				PROG_NAME		IN VARCHAR2 DEFAULT NULL);

PROCEDURE ADD_LOG(DESCR  		IN VARCHAR2,
				vLOG_THEME		IN VARCHAR2,
				vLOG_TYPE		IN VARCHAR2 DEFAULT NULL,
				RUN_ID 			IN NUMBER 	DEFAULT NULL,
				DESCR_CLOB		IN CLOB 	DEFAULT NULL);

PROCEDURE ADD_LOG_CLOB(DESCR_CLOB  	IN CLOB,
					LOG_THEME_ID	IN NUMBER,
					LOG_TYPE_ID		IN NUMBER DEFAULT NULL,
					RUN_ID 			IN NUMBER DEFAULT NULL);

PROCEDURE DEB(DESCR IN VARCHAR2);

PROCEDURE DEBC(DESCR_CLOB IN CLOB);

PROCEDURE CLEAR_LOGS_JOB;

PROCEDURE CLEAR_LOGS(nLOG_THEME_ID IN NUMBER);

END PKG_LOGS;